name             'ns'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ns'
long_description 'Installs/Configures ns'
version          '0.1.0'
